### PR TITLE
fix warnings and errors compiling for node v12.0.0

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by ukrbublik** [comment]
But with changes compiling for old versions of nodejs will fail. As now for CircleCI (configured for nodejs 4)

Btw do you think there can be use for this lib in Nodejs 12? Since it has threads and SharedArrayBuffer.

**Comment by trxcllnt** [comment]
@ukrbublik thanks for reviewing. I'm not super familiar with nan nor older versions of v8, but I've encountered this problem in other libraries I PR'd as well, so when I find a backwards-compatible solution I'll update this PR.

You're right that node itself now has threads and SAB, but using posix shared memory still has advantages:

1. posix shm is sometimes necessary for zero-copy interop with non-node systems (e.g. databases, other languages like python/OpenCL), it can be configured and tuned at the machine level, and VMs can use posix shared memory in Docker and cloud environments.
2. Selfishly, I'd rather avoid rewriting existing, proven code if possible just to use node v12 :-)

**Comment by trxcllnt** [comment]
@ukrbublik ok! looks like `ToChecked` is an alias for `FromJust`, and using that method fixes the build errors.

**Comment by ukrbublik** [comment]
Thanks!

**Pull request merged**
